### ISSUE TITLE
xnat-web tomcat fails to start with feature/dependency-mgmt branch 

### ISSUE THREAD

**Issue by lalithvaka** [NrgXnat/xnat-docker-compose#75]
**Describe the bug**
xnat-web container comes up but the xnat site does not come up. trafik dashboard is up
Note: Opening a new issue for the continuation of [issue](https://github.com/NrgXnat/xnat-docker-compose/issues/74) is closed

**To Reproduce**
$ git clone https://github.com/NrgXnat/xnat-docker-compose
$ cd xnat-docker-compose
$ git checkout features/dependency-mgmt
copied defaut.env to .env file
$ ./gradlew composeBuild composeUp
+--------------+----------------+-----------------+
| Name         | Container Port | Mapping         |
+--------------+----------------+-----------------+
| xnat-traefik | 80             | 172.20.0.1:80   |
| xnat-traefik | 8080           | 172.20.0.1:8080 |
+--------------+----------------+-----------------+
| xnat-web     | 8000           | 172.20.0.1:8000 |
| xnat-web     | 8104           | 172.20.0.1:8104 |
| xnat-web     | 8144           | 172.20.0.1:8144 |
+--------------+----------------+-----------------+
All the 3 containers up 

4. xnat-web / tomcat does not come up properly with default settings.
Errors from the xnat-web errors
```
Apr 21, 2021 4:17:05 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
INFO: OpenSSL successfully initialized [OpenSSL 1.1.1d  10 Sep 2019]
Apr 21, 2021 4:17:05 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-apr-8080"]
Apr 21, 2021 4:17:05 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 672 ms
Apr 21, 2021 4:17:05 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Catalina]
Apr 21, 2021 4:17:05 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.108
Apr 21, 2021 4:17:05 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
Debugger failed to attach: handshake failed - connection prematurally closed
Apr 21, 2021 4:17:15 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Apr 21, 2021 4:17:18 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Apr 21, 2021 4:17:18 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
Apr 21, 2021 4:17:18 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [12,948] ms
Apr 21, 2021 4:17:18 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-apr-8080"]
Apr 21, 2021 4:17:18 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 13012 ms
```

```
root@eee2582e9503:/usr/local/tomcat/logs# ls
catalina.2021-04-21.log  host-manager.2021-04-21.log  localhost.2021-04-21.log	localhost_access_log.2021-04-21.txt  manager.2021-04-21.log
root@eee2582e9503:/usr/local/tomcat/logs# cat localhost.2021-04-21.log
Apr 21, 2021 4:17:15 PM org.apache.catalina.core.ApplicationContext log
INFO: 2 Spring WebApplicationInitializers detected on classpath
Apr 21, 2021 4:17:15 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Apr 21, 2021 4:17:18 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'properties' defined in org.nrg.xnat.initialization.PropertiesConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.support.PropertySourcesPlaceholderConfigurer]: Factory method 'properties' threw exception; nested exception is java.lang.RuntimeException: No XNAT home specified in any of the accepted locations: ${xnat.config}/, ${xnat.config.home}/xnat-conf.properties, ${xnat.home}/config/xnat-conf.properties, ${XNAT_HOME}/config/xnat-conf.properties, ${HOME}/xnat/config/xnat-conf.properties, ${HOME}/config/xnat-conf.properties
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1176)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1071)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:151)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5126)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5653)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1007)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:983)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:639)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1128)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.support.PropertySourcesPlaceholderConfigurer]: Factory method 'properties' threw exception; nested exception is java.lang.RuntimeException: No XNAT home specified in any of the accepted locations: ${xnat.config}/, ${xnat.config.home}/xnat-conf.properties, ${xnat.home}/config/xnat-conf.properties, ${XNAT_HOME}/config/xnat-conf.properties, ${HOME}/xnat/config/xnat-conf.properties, ${HOME}/config/xnat-conf.properties
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 27 more
```

**Expected behavior**
The Xnat site to come up with default settings

**Docker server environment (please complete the following information):**
Host OS: - RHEL 7.7
Docker version - 20.10.6, build 370c289
docker-compose version -- version 1.29.1, build c34c88b2
Anything else? Java 8

**Configuration:**
Environment settings: default
Configuration: .manifest-XNAT-ML-18.json

**Comment by timrosenow** [comment]
I had the same issue: this is an excerpt from the docker-compose output:

```
Status: Downloaded newer image for postgres:12.2-alpine
 ---> ae192c4d3ada
Step 2/3 : RUN if [ ! -z ${POSTGRES_GID} && ${POSTGRES_GID} != 70 ]; then         sed -i'' -E 's/postgres:x:70:postgres/postgres:x:'${POSTGRES_GID}':postgres/' /etc/group;         sed -i'' -E 's/postgres:x:70:70:/postgres:x:'${POSTGRES_UID}':'${POSTGRES_GID}':/' /etc/passwd;     fi;
 ---> Running in 3cd8033dfe44
sh: missing ]
Removing intermediate container 3cd8033dfe44
 ---> de630a803e81
Step 3/3 : ADD --chown=postgres:postgres XNAT.sql /docker-entrypoint-initdb.d/
 ---> 1f189ecb93c5
Successfully built 1f189ecb93c5
Successfully tagged xnat-db:latest
WARNING: Image for service xnat-db was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
```
